// FETCH POSTS
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
// ADD
export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";
export const ON_PROGRESS = "ON_PROGRESS";
// UPDATE_POSTS
export const UPDATE_POST = "UPDATE_POST";
// LIKE
export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST"; //not in use
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"; //not in use
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE"; //not in use
// COMMENT
export const NEW_COMMENT_START = "NEW_COMMENT_START";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_FAILURE = "NEW_COMMENT_FAILURE";
// LIKE_COMMENT
export const LIKE_COMMENT = "LIKE_COMMENT";
// REPLY_COMMENT
export const REPLY_COMMENT = "REPLY_COMMENT";
// UPDATE_COMMENT
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_POST = "DELETE_POST"
