export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";
export const ON_PROGRESS = "ON_PROGRESS";
export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST"; //not in use
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"; //not in use
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE"; //not in use


