export const FETCH_POSTS = "FETCH_POSTS"
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS"
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR"
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST"