export const OPEN_NOTIFICATIONS_DD = "OPEN_NOTIFICATIONS_DD"
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION"
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"
export const SET_NOTIFY = "SET_NOTIFY"

