// LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
// GET_USER
export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
// ACCEPT REQUEST
export const ACCEPT_REQUEST_START = "ACCEPT_REQUEST_START";
export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const ACCEPT_REQUEST_FAILURE = "ACCEPT_REQUEST_FAILURE";
// REJECT REQUEST
export const REJECT_REQUEST_START = "REJECT_REQUEST_START";
export const REJECT_REQUEST_SUCCESS = "REJECT_REQUEST_SUCCESS";
export const REJECT_REQUEST_FAILURE = "REJECT_REQUEST_FAILURE";
// UNFRIENDS
export const UNFRIEND_START = "UNFRIEND_START";
export const UNFRIEND_SUCCESS = "UNFRIEND_SUCCESS";
export const UNFRIEND_FAILURE = "UNFRIEND_FAILURE";

// UPDATE_USER
export const UPDATE_USER = "UPDATE_USER";

export const SET_ACTIVE = "SET_ACTIVE";

