export const GET_PROFILE_START = "GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";
// fetch profile post
export const FETCH_USER_POSTS_REQUEST = "FETCH_USER_POSTS_REQUEST";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const FETCH_USER_POSTS_ERROR = "FETCH_USER_POSTS_ERROR";
// friendRequest
export const FRIEND_REQUEST_START = "FRIEND_REQUEST_START";
export const FRIEND_REQUEST_SUCCESS = "FRIEND_REQUEST_SUCCESS";
export const FRIEND_REQUEST_FAILURE = "FRIEND_REQUEST_FAILURE";
// request details
export const GET_REQUEST_DETAILS_START = "GET_REQUEST_DETAILS_START";
export const GET_REQUEST_DETAILS_SUCCESS = "GET_REQUEST_DETAILS_SUCCESS";
export const GET_REQUEST_DETAILS_FAILURE = "GET_REQUEST_DETAILS_FAILURE";
