// GET_PROFILE
export const GET_PROFILE_START = "GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";
// ON_PROGRESS
export const ON_PROGRESS = "ON_PROGRESS";
// FETCH_USER_POSTS
export const FETCH_USER_POSTS_REQUEST = "FETCH_USER_POSTS_REQUEST";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const FETCH_USER_POSTS_ERROR = "FETCH_USER_POSTS_ERROR";
// FRIENDS_REQUEST
export const FRIEND_REQUEST_START = "FRIEND_REQUEST_START";
export const FRIEND_REQUEST_SUCCESS = "FRIEND_REQUEST_SUCCESS";
export const FRIEND_REQUEST_FAILURE = "FRIEND_REQUEST_FAILURE";
// LIKE_POST_SUCCESS
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
// NEW_COMMENT_SUCCESS
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";

// LIKE_COMMENT
export const LIKE_COMMENT = "LIKE_COMMENT";
// UPDATE_PROFILE
export const UPDATE_PROFILE = "UPDATE_PROFILE";
// TAB
export const TAB = "TAB";
// CLEAR_USER
export const CLEAR_USER = "CLEAR_USER";

// request details
// export const GET_REQUEST_DETAILS_START = "GET_REQUEST_DETAILS_START";
// export const GET_REQUEST_DETAILS_SUCCESS = "GET_REQUEST_DETAILS_SUCCESS";
// export const GET_REQUEST_DETAILS_FAILURE = "GET_REQUEST_DETAILS_FAILURE";
